### PR TITLE
BreakOut-Sajeg

### PR DESCRIPTION
**Pull request by Sajeg**
Here is my submission. Thank you for doing this. :)

### Submission Files:
- [x] I have created a folder named `{Game name}-{Your name}` with my game files, containing:
  - [x] A folder named `source` with my source code.
  - [x] A folder named `build` with my build files (if my project needs a build to run).
  - [x] A `README.md` file with setup and play instructions.
    - [x] The `README.md` includes links to dependencies and photos if necessary.
    - [x] The instructions are clear and assume no prior knowledge.

### Please fill out the following:
- Link to the GitHub repo where you developed the project: https://github.com/Sajeg/BreakOut
- Approximate number of hours spent on the project: 38
- Brief description of the project (1-3 sentences): A game where you need to escape the dungeon through talking with the NPCs, that are powered by a Large Language Model.
- If applicable, GitHub username of your teammate: Only me @Sajeg

### Final Steps:
- [x] I have forked the repo and uploaded my submission folder to the `submissions` folder on my fork.
- [x] I have named my pull request `{Game name}-{Your name}`.

### CODE REVIEW

**Comment by evan-gan** [comment]
Hello! 
It looks like you are missing a readme.md and some info for your in your PR. 

Could you please review [the instructions](https://github.com/hackclub/Arcade-Game-Jam?tab=readme-ov-file#how-to-submit-to-the-jam) and ensure you have submitted everything correctly? Please reply here when you have filled everything out.

Thanks!

**Comment by evan-gan** [comment]
I just created a checklist for PR's. Going forwards, it will be automatically inserted into PR's but since it was not for yours here it is:
_(You can copy and paste it into your original PR comment)_
```
<!-- Hey! Please also make sure to read the readme.md of this repo for more detailed instructions -->


<!-- Replace "[ ]" with "[x]" to mark as checked. You must ensure everything is correct, and then check it off before submitting -->
### Submission Files:
- [ ] I have created a folder named `{Game name}-{Your name}` with my game files, containing:
  - [ ] A folder named `source` with my source code.
  - [ ] A folder named `build` with my build files (if my project needs a build to run).
  - [ ] A `README.md` file with setup and play instructions.
    - [ ] The `README.md` includes links to dependencies and photos if necessary.
    - [ ] The instructions are clear and assume no prior knowledge.

### Please fill out the following:
- Link to the GitHub repo where you developed the project: 
- Approximate number of hours spent on the project: 
- Brief description of the project (1-3 sentences): 
- If applicable, GitHub username of your teammate: 

### Final Steps:
- [ ] I have forked the repo and uploaded my submission folder to the `submissions` folder on my fork.
- [ ] I have named my pull request `{Game name}-{Your name}`.

**Comment by Sajeg** [comment]
Okay thanks. I thought the Play instructions readme should be in the builds directory or what read me am I missing?

**Comment by evan-gan** [comment]
If you could just move your readme.md up one folder into your BreakOut-Sajeg folder that would be great! Then you should be set

**Comment by Sajeg** [comment]
Okay I moved it. Sorry, that it took so long. Let me know if you need anything else.

**Pull request merged**
