### PR TITLE
Octodive-Nina

### PR DESCRIPTION
**Pull request by Caramel4764**
Note: I really hope I'm doing this correctly. I struggled to figure this out because I apparently had 100 files according to github which I still don't think is true but whatever.

### Submission Files:
- [x] I have created a folder named `{Game name}-{Your name}` with my game files, containing:
  - [x] A folder named `source` with my source code.
  - [x] A folder named `build` with my build files (if my project needs a build to run).
  - [x] A `README.md` file with setup and play instructions.
    - [x] The `README.md` includes links to dependencies and photos if necessary.
    - [x] The instructions are clear and assume no prior knowledge.

### Please fill out the following:
- Link to the GitHub repo where you developed the project: 
https://github.com/Caramel4764/Octodive

- Approximate number of hours spent on the project: 
I think I have around 60-70ish hours

- Brief description of the project (1-3 sentences): 
Octodive is an endless runner where the player plays as an octopus and try to go through loops for points and make it as far as possible.

- If applicable, GitHub username of your teammate: 
Solo project so no teammate.

### Final Steps:
- [x] I have forked the repo and uploaded my submission folder to the `submissions` folder on my fork.
- [x] I have named my pull request `{Game name}-{Your name}`.

### CODE REVIEW

**Comment by evan-gan** [comment]
Hello!
It looks like you included a 4 additional files than the one's required. Could you please remove them? Here is a screenshot with a red dash next to the extra files.
Screenshot 2024-08-22 at 8 59 29 AM

**Comment by Caramel4764** [comment]
Hi!
Sorry about the 4 additional file. I was really struggling to embed my game
repo files because it was over 100 files which the drag and drop do not
support. The uploaded attempt was my 3rd attempt because the first 2 kept
saying not a github repo. That’s why I had 3 commits to constantly test if
it would let me commit. I’ll try to remove them later on the day. It’s
7:35AM in the morning pst for me and I have school with unfinished homework
because I stayed up making final changes. I believe there’s around 24 more
hours for submission so this should hopefully be fine. This email is just
letting you know that I definitely saw this email.
Thank you for reading such a long email,
Nina

**Comment by Caramel4764** [comment]
Is this okay now?
Screenshot 2024-08-22 171421

**Comment by evan-gan** [comment]
Yep! Looks good

**Pull request merged**
